Repository k8-proxy/k8-data-visualization, pull requests merged in 2020-10, with the labels that each got.

#102 widgets for pr and issues
  upwork-devs/moses-mugo/README.md
  upwork-devs/moses-mugo/data/pull_requests.csv
  upwork-devs/moses-mugo/main.py
  upwork-devs/moses-mugo/models/issues.py
  upwork-devs/moses-mugo/models/pull_requests.py
  upwork-devs/moses-mugo/models/repos.py
  upwork-devs/moses-mugo/models/transform.py
  upwork-devs/moses-mugo/notebooks/issues.ipynb
  upwork-devs/moses-mugo/notebooks/pull_requests.ipynb
  upwork-devs/moses-mugo/requirements.txt
Labels: ready-for-review

#100 Updating visualization Notebooks, adding theme, table of contents, hiding code - Lwasampijja baker
  upwork-devs/README.md
  upwork-devs/lwasampijja-baker/All_Progress_Issues.ipynb
  upwork-devs/lwasampijja-baker/Visualise_Zenhub_Pipelines.ipynb
  upwork-devs/lwasampijja-baker/Visuals.ipynb
  upwork-devs/lwasampijja-baker/issues.ipynb
  upwork-devs/lwasampijja-baker/zen_pipe.py
Labels: ready-for-review

#101 Create TOC and Updates. Closes #86
  upwork-devs/Pappaterra-Lucia/.gitignore
  upwork-devs/Pappaterra-Lucia/Generate_files.ipynb
  upwork-devs/Pappaterra-Lucia/Make_PowerPoint_Presentation.ipynb
  upwork-devs/Pappaterra-Lucia/Org_Chart_Vis.ipynb
  upwork-devs/Pappaterra-Lucia/PR_report.ipynb
  upwork-devs/Pappaterra-Lucia/README.md
  upwork-devs/Pappaterra-Lucia/images/glasswall_logo.png
  upwork-devs/Pappaterra-Lucia/modules/aux_plot_func.py
  upwork-devs/Pappaterra-Lucia/modules/config.json
  upwork-devs/Pappaterra-Lucia/modules/file_converter.py
  upwork-devs/Pappaterra-Lucia/modules/gitpulls.py
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
  upwork-devs/Pappaterra-Lucia/outputs/Projects Team Structure.pptx
Labels: ready-for-review

#103 Customize jupyter-notebooks in the glasswall style. Closses #97
  upwork-devs/Pappaterra-Lucia/modules/custom.css
Labels: ready-for-review

#107 Enhance PR_report notebook – include label. Closes #98.
  upwork-devs/Pappaterra-Lucia/PR_report.ipynb
  upwork-devs/Pappaterra-Lucia/README.md
  upwork-devs/Pappaterra-Lucia/modules/config.json
  upwork-devs/Pappaterra-Lucia/modules/gitpulls.py
Labels: ready-for-review

#113 PR report enhancement. Closes #110
  upwork-devs/Pappaterra-Lucia/PR_report.ipynb
  upwork-devs/Pappaterra-Lucia/modules/gitpulls.py
Labels: ready-for-review

#114 added zenhub boards data
  upwork-devs/moses-mugo/notebooks/zenhub_boards.ipynb
  upwork-devs/moses-mugo/requirements.txt
Labels: ready-for-review

#115 Enhace powerpoint presentations. Create new presentation for Daily Reports. Closes #108
  upwork-devs/Pappaterra-Lucia/.gitignore
  upwork-devs/Pappaterra-Lucia/Daily_Update.ipynb
  upwork-devs/Pappaterra-Lucia/Generate_files.ipynb
  upwork-devs/Pappaterra-Lucia/Make_PowerPoint_Presentation.ipynb
  upwork-devs/Pappaterra-Lucia/README.md
  upwork-devs/Pappaterra-Lucia/images/glasswall_logo2.png
  upwork-devs/Pappaterra-Lucia/modules/credentials.json
  upwork-devs/Pappaterra-Lucia/modules/daily_updates.py
  upwork-devs/Pappaterra-Lucia/modules/file_converter.py
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
Labels: ready-for-review

#127 fixes path errors in notebooks
  upwork-devs/moses-mugo/models/issues.py
  upwork-devs/moses-mugo/models/pull_requests.py
  upwork-devs/moses-mugo/models/repos.py
  upwork-devs/moses-mugo/models/transform.py
  upwork-devs/moses-mugo/notebooks/issues.ipynb
  upwork-devs/moses-mugo/notebooks/pull_requests.ipynb
  upwork-devs/moses-mugo/notebooks/zenhub_boards.ipynb
Labels: ready-for-review

#128 Update for Daily Report presentations
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
Labels: ready-for-review

#131 Enhance presentations
  upwork-devs/Pappaterra-Lucia/Daily_Update.ipynb
  upwork-devs/Pappaterra-Lucia/Make_PowerPoint_Presentation.ipynb
  upwork-devs/Pappaterra-Lucia/README.md
  upwork-devs/Pappaterra-Lucia/images/glasswall_logo2.png
  upwork-devs/Pappaterra-Lucia/modules/aux_plot_func.py
  upwork-devs/Pappaterra-Lucia/modules/daily_updates.py
  upwork-devs/Pappaterra-Lucia/modules/file_converter.py
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
Labels: ready-for-review

#139 Daily Report enhancement
  upwork-devs/Pappaterra-Lucia/Daily_Update.ipynb
  upwork-devs/Pappaterra-Lucia/modules/daily_updates.py
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
Labels: enhancement, ready-for-review

#141 Fix bug (Closes #136)
  upwork-devs/Pappaterra-Lucia/Make_PowerPoint_Presentation.ipynb
  upwork-devs/Pappaterra-Lucia/modules/file_converter.py
  upwork-devs/Pappaterra-Lucia/modules/power_point.py
Labels: ready-for-review

#142 Update README.md
  upwork-devs/moses-mugo/README.md
Labels: Ready for review
